### ISSUE TITLE
Problem installing from npm / yarn on Windows 11

### ISSUE THREAD

**Issue by anpelodo** [sidwebworks/zod-xlsx#1]
I previosly installed zod and xlsx, 

I use this command for installing.

`yarn add zod-xlsx`

error

>  D:\juanf\Desktop\OKWEB\test\node_modules\zod-xlsx: Command failed.
> Exit code: 1
> Command: npx husky-init
> Arguments:
> Directory: D:\juanf\Desktop\OKWEB\test\node_modules\zod-xlsx
> Output:
> husky-init updating package.json
>   "husky install" command already exists in prepare script, skipping.
> fatal: not a git repository (or any of the parent directories): .git
> C:\Users\juanf\AppData\Local\npm-cache\_npx\1ab9c0f68ac2536e\node_modules\husky\lib\index.js:43
>         throw new Error(`can't create hook, ${dir} directory doesn't exist (try running husky install)`);
>         ^
> 
> Error: can't create hook, .husky directory doesn't exist (try running husky install)
>     at set (C:\Users\juanf\AppData\Local\npm-cache\_npx\1ab9c0f68ac2536e\node_modules\husky\lib\index.js:43:15)
>     at Object.<anonymous> (C:\Users\juanf\AppData\Local\npm-cache\_npx\1ab9c0f68ac2536e\node_modules\husky-init\lib\bin.js:17:17)
>     at Module._compile (node:internal/modules/cjs/loader:1126:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
>     at Module.load (node:internal/modules/cjs/loader:1004:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:17:47
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

this error is the same in npm and yarn.

`yarn -v` : 1.22.19
`npm -v`: 16.17.0
`node -v`: 8.19.1

**Comment by sidwebworks** [comment]
@anpelodo Hey there, thanks for reporting the issue. I forgot to remove the `prepare` and `postinstall` scripts for the package. I have fixed this in the latest release and improved support for async batch processing.

Can you please try reinstalling the package using the following command

```sh
yarn add zod-xlsx@latest
```

**Comment by anpelodo** [comment]
@sidwebworks Of course, no problem. definitly that solved the problem. Thanks!
